apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ms-security-copilot-plugin
  tags:
    - openapi
    - microsoft
    - security-copilot
    - integration
    - nist
spec:
  type: artifact
  lifecycle: production
  owner: data-science
  system: jamf-pro-server
